### PR TITLE
Correctly handle error type vector data from prometheus for pie charts.

### LINKED ISSUE #293: Incorrect expression in pie chart leads to JS error
```
TypeError: undefined is not a function
    at redrawGraph (http://promdash/assets/application-169b81fb456465d5b699b279096661d6.js:3302:17)
    at http://promdash/assets/application-169b81fb456465d5b699b279096661d6.js:3359:9
    at h.$broadcast (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular.min.js:103:281)
    at $window.onresize (http://promdash/assets/application-169b81fb456465d5b699b279096661d6.js:2042:12)
```

### PR DESCRIPTION
**Pull request by stuartnelson3**
fixes #293

### CODE REVIEW

**Comment by stuartnelson3** [comment]
@juliusv

**Comment by juliusv** [comment]
This'll need updating to accomodate https://github.com/prometheus/promdash/pull/294

**Comment by stuartnelson3** [comment]
updated

**Comment by juliusv** [comment]
:+1: but "We can’t automatically merge this pull request."

**Comment by stuartnelson3** [comment]
fixed

**Pull request merged**
