### PR TITLE
Add container-fluid container class and apply to markup container.

### PR DESCRIPTION
**Pull request by stuartnelson3**
@grobie @juliusv

### CODE REVIEW

**Comment by juliusv** [comment]
This makes the dashboard and server overview pages look broken (almost no margins at all).

**Comment by stuartnelson3** [comment]
hm, so only on the `dashboard#show` page?

**Comment by grobie** [comment]
Yes, this was the reason I didn't publish it.

**Comment by juliusv** [comment]
Yeah, it should only be on the `dashboard#show` page. Also, do we have consensus on being ok with making non-fullscreen dashboards suddenly look completely different for people? I guess it's ok because it doesn't affect the wall-screen fullscreen view...

**Comment by grobie** [comment]
Fine with me to have it only on dashboard#show as well instead of fixing the margin on the other pages.

**Comment by juliusv** [comment]
SGTM too

**Comment by stuartnelson3** [comment]
failed test is re-running, but all should be good.

even wrote a couple tests for the test ~~nazi~~ fairy

**Comment by grobie** [comment]
:+1: great work!

**Pull request merged**
