### PR TITLE
HTML-escape label values in hover details and legend.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@stuartnelson3

**Comment by stuartnelson3** [comment]
looks good, but let's take 5min to write some unit tests together tomorrow when you get in

**Comment by juliusv** [comment]
@stuartnelson3 Some extra ones, you mean? (I'm actually still waiting on Travis to tell me whether the new ones work, since somehow the webdriver stuff hangs on me locally)

**Comment by stuartnelson3** [comment]
unit tests, not feature specs

**Comment by juliusv** [comment]
Ah, ok. Yes, and it's also only testing the legend string so far, not the hover detail yet. Not sure how feasible the latter is though.

**Comment by juliusv** [comment]
@stuartnelson3 Woot, thanks for the extra unit test. Good to merge?

**Comment by stuartnelson3** [comment]
:dango:

**Pull request merged**
