### PR TITLE
Fix JS errors related to missing server selection.

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/prometheus/promdash/issues/276

### CODE REVIEW

**Comment by juliusv** [comment]
@stuartnelson3

**Comment by juliusv** [comment]
@stuartnelson3 Could we work on tests together for this tomorrow? It'll be much faster, I suspect :)

**Comment by stuartnelson3** [comment]
haha yes of course

**Comment by juliusv** [comment]
:+1: from @stuartnelson3 in person sitting next to me :)

**Pull request merged**
