### PR TITLE
Minor UI changes to the Dashboard

### PR DESCRIPTION
**Pull request by samstarling**
The visual changes here are fairly minor, but there are a few differences under the hood – I'll list those below.

<h4>Before</h4>
before

<h4>After</h4>
after

#### Changes

* Per-graph popups now have slightly cleaner formatting: inputs and controls use more of the available space.
* Tidied up some of the spacing between elements to be more uniform, same goes for the fullscreen view.
* Slightly improved use of Bootstrap classes like `row` and `col-...`.
* Some whitespace changes - sorry for not keeping these separate.

Please let me know if you'd like me to squash/tidy these commits. I left them separate for now, in case you take particular issue with any of them individually. There's probably more where this came from, but I thought I'd keep it simple for now.

Thanks!

/cc @juliusv @stuartnelson3 @grobie

### CODE REVIEW

**Comment by samstarling** [comment]
FYI: I haven't run the tests yet!

**Comment by stuartnelson3** [comment]
have you checked visually between safari/chrome/firefox?

**Comment by samstarling** [comment]
Still to do:

[ ] Check in Safari, Chrome and Firefox
[ ] Run the tests

**Comment by samstarling** [comment]
Looks good in Firefox and Safari.

**Comment by juliusv** [comment]
@samstarling Thanks! Taking a closer look now.

I noticed this on the index (directories) page:

dir_page

The action icons look different / broken...

**Comment by juliusv** [comment]
Hmm, same for the actions on a graph, but not sure yet why exactly.

**Comment by juliusv** [comment]
The problem went away for me with a fresh checkout of PromDash. Apologies.

**Comment by juliusv** [comment]
Getting this weird extra element underneath the expression in the Datasources tab of the graph now:

ui_glitch

Looking at its DOM, it seems to be related to the typeahead autocomplete plugin...

**Comment by stuartnelson3** [comment]
@juliusv @samstarling the problem with the typeahead is due to it being upgraded in a previous PR. Looking at the source code, the upgraded version of the typeahead assumes a version of angular higher than what we are using in promdash.

a previous attempt at upgrading angular was abandoned after we encountered weird, linux-only errors.

the easiest solution would be to try to upgrade our copy of angular again.

the more difficult solution is either to edit our vendored copy of ui-bootstrap, or roll back to a previous version.

**Comment by juliusv** [comment]
I noticed this PR solves the scrollbar part of https://github.com/prometheus/promdash/issues/453.

Since the autocomplete problem exists with or without this PR, I'll merge this to fix at least the scrollbar.

Thanks!

**Comment by samstarling** [comment]
@juliusv Thanks! If there's anything here that looks like it's broken something, I tried to make the commits small and atomic, so hopefully you'll be able to pick out the "bad" commit if things break. I did also notice it had the side effect of making the drag-and-drop rearrangement a little smoother. Give me a shout if things look broken, I'm aware I didn't do too well with this last time :smile:

**Comment by juliusv** [comment]
@samstarling No problem, thanks for this :)

**Pull request merged**
