### PR TITLE
Add pie charts to promdash

### PR DESCRIPTION
**Pull request by stuartnelson3**
See title. Plz comment with anything I've missed, or additional functionality you would like like.

requested in #114 

@tomcz @juliusv @grobie @ohookins

### CODE REVIEW

**Comment by trompx** [comment]
Hello,

Is there a way to display % and the stat value (like the haproxy_server_http_responses_total) in a promdash pie chart ?
Something like http://stackoverflow.com/questions/28306308/how-to-draw-labels-on-dimple-js-donut-or-pie-chart/28342150#28342150 

If not on the graph is there a way to put this info in the legend ?

**Comment by trompx** [comment]
Other problem, on latest version of chrome (I haven't tested on other browsers), when I set the 2 or 3 columns layout (with any aspect ratio), when I hover the pie chart, tooltip is not showing correctly for some parts.

pie chart overflow

When the size of the chart is bigger all is fine though.

**Comment by stuartnelson3** [comment]
>Is there a way to display % and the stat value (like the haproxy_server_http_responses_total) in a promdash pie chart ?
Something like http://stackoverflow.com/questions/28306308/how-to-draw-labels-on-dimple-js-donut-or-pie-chart/28342150#28342150

hey, currently there is no way to edit the pop-up display. if percentage is something you're interested in, it could be added [here](https://github.com/prometheus/promdash/blob/master/app/assets/javascripts/angular/directives/pie_chart.js#L52-L56) as an additional value.

>If not on the graph is there a way to put this info in the legend ?

the legend information can be modified in the legend tab on the pie chart:

image

**Comment by trompx** [comment]
Thanks for pointing to the additional value @stuartnelson3.

As for the legend tab, I already use it. I meant is there a way to get the value (not one of the label like "job", "instance" etc.) but for instance display "72" in the legend for haproxy_frontend_connections_total stat.

**Comment by stuartnelson3** [comment]
unless it's a value being returned from prometheus, no

**Pull request merged**
