### PR TITLE
Upgrade Selenium and Capybara

### PR DESCRIPTION
**Pull request by samstarling**
@stuartnelson3 This fixed the problems I was having with running the tests locally. People may need to upgrade Firefox, when moving to newer Selenium/Capybara versions. Once upgraded, this also revealed that I'd missed out the `.woff2` version of Glyphicons.

### CODE REVIEW

**Comment by samstarling** [comment]
I don't know what I did to the build :cry:

**Comment by stuartnelson3** [comment]
tests are failing for me locally and on ci

**Comment by stuartnelson3** [comment]
you broke it.

**Comment by juliusv** [comment]
Any news on this one? I really don't understand much about these testing frameworks :)

**Comment by samstarling** [comment]
@juliusv I have a bit of spare time today, let me have a look!

**Comment by samstarling** [comment]
I'm going to close this PR and replace it with a new one - it's drifted further from `master` and it does two very separate things. New one incoming shortly!

**Pull request closed without merging**
