### PR TITLE
Recommend Grafana at very top of PromDash README.md

### PR DESCRIPTION
**Pull request by juliusv**
@grobie @stuartnelson3

### CODE REVIEW

**Comment by stuartnelson3** [comment]
You could probably make it stronger and just say promdash is deprecated/unmaintained, as I doubt it will get any attention

**Comment by juliusv** [comment]
@stuartnelson3 How do you like it now?

**Comment by stuartnelson3** [comment]
image

probably for the best, as your readme change broke the build 

:+1: :cry:

**Comment by juliusv** [comment]
Haha! Restarted the build.

**Pull request merged**
